name: ROS2 ovis build
run-name: ${{ github.actor }} is working on ROS2 ovis build
on: [push]
jobs:
  Build_ovis:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build docker compose
      run: |
        docker compose run --user root devcontainer bash -c "colcon build"

