# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ovis_controller:
      type: ovis_controller/OvisController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ovis_controller:
  ros__parameters:
    joints:
      - ovis_joint_1
      - ovis_joint_2
      - ovis_joint_3
      - ovis_joint_4
      - ovis_joint_5
      - ovis_joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity